### PR TITLE
add lines between gaps in data

### PR DESCRIPTION
**Pull request by daanlouter**
Requested by a user. It basically draws lines between missing data values. Bit of a tricky subject, as there's also the animation of the circles. Would be great if you could take a quick look at this @theduncanclark! (you can enable it by ticking "show missing lines" in line styles settings panel)

### CODE REVIEW

**Comment by timbrock** [comment]
I'm not sure that's a particularly helpful name for it.

**Comment by daanlouter** [comment]
which name?

**Comment by timbrock** [comment]
"show missing lines" doesn't convey that ticking the box will fill the space between missing points with a straight line.

**Comment by daanlouter** [comment]
Ah, good point. Any suggestions?

**Comment by timbrock** [comment]
"Break lines where points are missing" (this is obviously the reverse option).

**Pull request merged**
