### PR TITLE
Improvements to y axis. Fixes #29, fixes #49, fixes #20

### LINKED ISSUE #20: Only show the top {x} results
If you have a lot of data, and movement in the top 5 (people leaving and entering the top 5 a lot), it might be nice to filter/resize the y-axis to just show the top 5.

### LINKED ISSUE #29: Max rank should be calculated with double ranks in mind
So don't just use horses.length as max value
screen shot 2017-09-12 at 17 16 23

### LINKED ISSUE #49: Weird to have number suffix and not prefix

### PR DESCRIPTION
**Pull request by theduncanclark**
image

### CODE REVIEW

**Comment by theduncanclark** [comment]
Changing the name as combining a few things in this PR to avoid conflicts

**Comment by daanlouter** [comment]
Quickly tested this, and really nice new features. One suggestion: should we add 1 to the min/max rank values so that Min rank 1 actually means 1 (instead of 2). Seems confusing to non-techies.

**Comment by daanlouter** [comment]
Looks good otherwise

**Comment by theduncanclark** [comment]
Yeah, the ranks are the ranks as displayed I think (not zero indexed) so all good 🙂

**Pull request merged**
