### PR TITLE
Use standard competition ranking when there are ties

### PR DESCRIPTION
**Pull request by timbrock**
- See [Ranking types](https://en.wikipedia.org/wiki/Ranking#Standard_competition_ranking_(%221224%22_ranking)).

### CODE REVIEW

**Comment by daanlouter** [comment]
Hmm. I personally think it's quite odd that there's a gap at the 5th position now.

screen shot 2018-08-27 at 10 52 23

**Comment by timbrock** [comment]
Why?

**Comment by annapowellsmith** [comment]
@timbrock I think if we make this the default it will surprise some users, like Daan - whereas people who are actively looking for competition ranking will be willing to look for it behind a settings toggle. Please could we make it a non-default option? (and, this is lower priority than republishing the template)

**Comment by timbrock** [comment]
> I think if we make this the default it will surprise some users, like Daan - whereas people who are actively looking for competition ranking will be willing to look for it behind a settings toggle. 

I still don't see how this is surprising in any way. It is the standard way of doing things (as the name suggests).

**Comment by timbrock** [comment]
Well, he said it looked odd. But I assumed that was more aesthetics.

**Comment by timbrock** [comment]
In favour of merging this:
- I think this what most people expect.
- @micycle thought the same.
- This is what happens in most competitions as far as I'm aware. It's definitely what happens in the Olympics.

Against merging this:
- @daanlouter thinks it looks odd.

**Comment by micycle** [comment]
It would be better if it said "4=" but then that might screw up your alignment

**Comment by timbrock** [comment]
You can now do competition or dense modes.

**Pull request merged**
