### PR TITLE
Handle blanks. Fixes #33

### LINKED ISSUE #33: Better handle empty columns and cells
If a cell is empty, the position in the chart is really weird. should probably just ignore that value. If a whole column is empty, it will break the viz.

bildschirmfoto 2017-10-02 um 17 22 53
bildschirmfoto 2017-10-02 um 17 22 36

### PR DESCRIPTION
**Pull request by theduncanclark**
@daanlouter – as discussed at length with @robinhouston in #33, I think this is the solution you were asking for. Bit fiddly so worth kicking the tyres but hopefully should be okay.

screen recording 2017-10-29 at 01 42 am

### CODE REVIEW

**Comment by daanlouter** [comment]
Oh nice! Thanks, will test now

**Comment by daanlouter** [comment]
This is great! It currently throws errors when inputting NaN value in the spreadsheet.

**Comment by theduncanclark** [comment]
Yes, makes sense – I didn't attempt to deal with anything except blanks! Presumably it should just treat NaN the same as blanks?

**Comment by daanlouter** [comment]
Yes, that's what I was thinking too.

**Comment by theduncanclark** [comment]
Done

**Comment by theduncanclark** [comment]
(Also removes commas and whitespace.)

**Pull request merged**
