### PR TITLE
Add setting to resize chart based on horse count. Fixes #114

### LINKED ISSUE #114: Add setting to adjust height based on amount of horses
ie. A visualisation with many horses will get taller so they all fit nicely. The height can be calculated as `number of horses * (circle radius + optional circle margin)`.

### PR DESCRIPTION
**Pull request by daanlouter**

### CODE REVIEW

**Comment by theduncanclark** [comment]
Yay!

Quick q … on the live version this label to the right doesn't get cropped:

image

On the new one it does:

image

These are both with all margins set to zero.

Looking at this made me realise I don't really understand what the margins are for. Can we remove them given the layout module?

**Comment by timbrock** [comment]
> Looking at this made me realise I don't really understand what the margins are for. Can we remove them given the layout module?

No (though I agree it's confusing). The layout module margins specify the space between the edges of the page and _all_ the content.  The chart margins specify the space between the edge of the plot area and the edge of the SVG graphic. Labels can bleed outside the plot area but not out of the content area and into the layout margin.

**Comment by daanlouter** [comment]
Re: removing margins. What Tim said.

Good spot about the cut offs, it looks like it used to calculate too much margins on the right hand side. The reason it's cut off now, is because I removed the circle stroke from the margin calculation. So it should be correct now for non-overlapping circles, but not yet for overlapping circles (which pushes the labels to the right). I'll have a look if I can adjust this.

**Comment by daanlouter** [comment]
I just added an extra right margin via the state property for now. We could probably do a better job at it, but for now this is quite similar to how it works in master. So @theduncanclark one for you to merge on your way to the office? :)

**Pull request merged**
