### PR TITLE
Frontload selected horses. Closes #45

### LINKED ISSUE #45: Bring marker for hovered line to top of stack
So it is fully visible, unlike here.

screen shot 2017-10-27 at 14 29 53

### PR DESCRIPTION
**Pull request by theduncanclark**

### CODE REVIEW

**Comment by timbrock** [comment]
It doesn't seem to actually fix #45.
screen shot 2017-11-03 at 09 52 15
screen shot 2017-11-03 at 09 52 23

**Comment by theduncanclark** [comment]
Do you mean it doesn't apply on hover? Yes, I meant to say, I did that on purpose to avoid mouseover circles appearing atop clicked circles. But on reflection we could frontload on hover except when there are selected circles, which is probably a nice compromise. Just pushed.

**Comment by timbrock** [comment]
I see...
screen shot 2017-11-03 at 10 06 21

Lines are in a separate group to circles, and they're only being brought to the top of their group. So, as is, lines will always disappear under circles.

**Comment by theduncanclark** [comment]
> Lines are in a separate group to circles, and they're only being brought to the top of their group. So, as is, lines will always disappear under circles.

Yep, correct, was designed that way on purpose! Means you can get the effect shown above for the green line in a tie-break scenario. I propose we live with that as it would be time consuming and fiddly to fix and it's not a serious problem.

**Comment by timbrock** [comment]
We could keep it that where for non-highlighted mode and "fix" it for highlighted items by cloning them to a new layer?

**Comment by daanlouter** [comment]
nov-03-2017 11-44-52

There's some weird stuff going on when trying to select a line that is currently tied

**Comment by theduncanclark** [comment]
Okay, weirdness hopefully fixed now. @timbrock – can you merge and republish. PwC are waiting for it!

**Pull request merged**
